### ISSUE TITLE
What is the best way to handle multiple text inputs?

### ISSUE THREAD

**Issue by ItoYo16u** [JetBrains/JWM#125]
Hi, I tried example application and read implementation.

I wonder what is the best way to handle multiple text inputs in a single window(e.g. switching focuses, editing multiple lines at the same time like vs code `alt + enter`. )

**Comment by tonsky** [comment]
This would be a task for a separate UI library. JWM only handles OS integration (windows, events), it does not draw/implements any widgets by itself.
