### ISSUE TITLE
Linux: fix flickering

### ISSUE THREAD

**Issue by Alex2772** [JetBrains/JWM#22]
- [x] #23

**Comment by SergeevPavel** [comment]
https://user-images.githubusercontent.com/4352041/124484534-318b5a00-ddb4-11eb-9199-fe7f5b97a45b.mp4

**Comment by SergeevPavel** [comment]
https://user-images.githubusercontent.com/4352041/126194291-0907eeed-add3-4dc5-9154-f84a2a989006.mp4

**Comment by SergeevPavel** [comment]
some resize glitches still present for me, but now there is no black rectangles.
`VSYNC` looks gray, despite on video.

**Comment by Alex2772** [comment]
Discussion moved to #54 to avoid confusion
