### ISSUE TITLE
Input Methods API research

### ISSUE THREAD

**Issue by tonsky** [JetBrains/JWM#33]

**Comment by tonsky** [comment]
This is what we need to support on macOS. Most of those are implemented by OS and will come automatically if we did things right. But the main idea of it is that text input is not a “char typed” anymore, it’s more like two-way protocol that can also decorate and edit already entered text by chunks.

Normal typing + unicode + keyboard layouts:

![33 43](https://user-images.githubusercontent.com/285292/125298815-cba95000-e328-11eb-8142-327342d2bc10.gif)

“Composing regions”. An umlaut is entered first and waiting for the second char before being combined together into a singel glyph. Partially-entered regions are normally decorated with underline (this case) or bg color:

![34 05](https://user-images.githubusercontent.com/285292/125299032-07441a00-e329-11eb-9713-b07d87112be0.gif)

On-screen keyboard. No physical keys were pressed

![35 01](https://user-images.githubusercontent.com/285292/125299082-14610900-e329-11eb-8738-dfce9d8df858.gif)

Touchbar/on-screen keyboard suggestions. Change already typed word, works by tracking what is currently word under cursor. Displayed with on-screen keyboard, but touchbar works the same:

![35 25](https://user-images.githubusercontent.com/285292/125299163-2d69ba00-e329-11eb-95ba-a4bc9930bb04.gif)

System-wide text replacement. Can be customized (`\shrug` is a custom one I made):

![36 51](https://user-images.githubusercontent.com/285292/125299246-42dee400-e329-11eb-9910-0ef05c2e299e.gif)

Emoji picker. Again, no physical keys were pressed (except for calling out emoji picker):

![37 43](https://user-images.githubusercontent.com/285292/125299325-568a4a80-e329-11eb-8dd1-b286a56ca66a.gif)

Smart quotes, graphical completion, word capitalization, auto-correction. All system-wide settings, all change text and can be “undone” if you are not happy with those changes:

![39 45](https://user-images.githubusercontent.com/285292/125299485-7b7ebd80-e329-11eb-91ec-c7085dd7bc44.gif)

**Comment by Alex2772** [comment]
In X11, there's no dedicated event for character processing. You should treat KeyPress event as a key press event and a keyboard character input event.

**Comment by Alex2772** [comment]
UPDATE: On *nix, there's IBus, an input framework that can serve complex languages like Chinese, Japanese, etc. It comes with GNOME 3.

**Comment by SergeevPavel** [comment]
in terms of API we could start from looking on AWT implementation/realisation, they have interface https://docs.oracle.com/javase/7/docs/api/java/awt/im/InputMethodRequests.html with bunch of method that client code should implement to describe to OS where is text input and which text is processed now

**Comment by EgorOrachyov** [comment]
In WinAPI, we have Input Method Manager (IMM). The IME allows computer users to enter complex characters and symbols, such as Japanese kanji characters, by using a standard keyboard.

Seems, like it is what we are looking for?

[LinksIMM](https://docs.microsoft.com/en-us/windows/win32/intl/input-method-manager)
[About IMM](https://docs.microsoft.com/en-us/windows/win32/intl/about-input-method-manager)

**Comment by tonsky** [comment]
https://firefox-source-docs.mozilla.org/editor/IMEHandlingGuide.html

**Comment by tonsky** [comment]
https://github.com/openjdk/jfx/blob/86b854dc367fb32743810716da5583f7d59208f8/modules/javafx.graphics/src/main/native-glass/mac/GlassView3D.m#L729

**Comment by tonsky** [comment]
https://github.com/mozilla/gecko-dev/blob/master/widget/cocoa/TextInputHandler.mm

**Comment by tonsky** [comment]
https://github.com/JetBrains/skiko/blob/fda59e1f8b96142c20fbf8bed015b3a4978cea70/skiko/src/jvmMain/objectiveC/macos/InputMethod.mm

**Comment by tonsky** [comment]
https://tedyin.com/posts/a-brief-intro-to-linux-input-method-framework/

**Comment by glyh** [comment]
Wayland seems to be left out
https://github.com/HumbleUI/HumbleUI/issues/86
https://wayland.app/protocols/input-method-unstable-v1
