### ISSUE TITLE
Linux X11/OpelGL status

### ISSUE THREAD

**Issue by tonsky** [JetBrains/JWM#54]
- [ ] Redraw is not synchronized with window update (black bars, edge triangles jump)
- [ ] Windows on multiple monitors use frame rate from the slowest monitor
- [ ] VSync text is not gray on 120 Hz
- [x] Multiple windows on a single monitor render at monitor refresh rate
- [x] FPS changes when moving between monitors
- [x] Resizing one window does not freeze another
- [x] Moving one window freezes another

Additional info:

- Ubuntu doesn't allow for different DPI on different monitors
- Firefox always renders at 60 Hz on any monitor
- #22

**Comment by Alex2772** [comment]
On KDE, window moving does not cause freezing on another window. Looks like it's a trait of GTK-based WMs.

Have you noticed lag when resizing? IMHO it's not smooth.

**Comment by tonsky** [comment]
Not smooth, but smoother than moving window. Probably nothing we can do, just mention it here for fuller picture
