### ISSUE TITLE
Set app icon

### ISSUE THREAD

**Issue by tonsky** [JetBrains/JWM#95]
TODO: Check AWT & JavaFX

Preliminary:

```
Window::setIcon(File)
```
~Window::setIcon(byte[])~

- [x] Windows
- [ ] Linux
- [x] macOS

**Comment by ItoYo16u** [comment]
Which image fomat should `SetIcon(File)` function support? 

( Windows native api(`hIcon`) seems to support only .ico format. )

**Comment by tonsky** [comment]
We were thinking of whatever native platform expects. That would mean ico for Windows, icns for macOS, not sure what (png?) for Linux

**Comment by tonsky** [comment]
Will be followed up by #135
