### ISSUE TITLE
Maximize/minimize/restore/setVisible

### ISSUE THREAD

**Issue by tonsky** [JetBrains/JWM#96]
Events:

- EventWindowMaximize
- EventWindowMinimize
- EventWindowRestore
- ~~EventWindowVisible(boolean)~~

Methods:

- Window::minimize
- Window::maximize
- Window::restore
- Rename show -> Window::setVisible(boolean)

Window:

- [x] Windows
- [x] Linux
- [x] macOS

**Comment by EgorOrachyov** [comment]
Windows SIZE event:
![image](https://user-images.githubusercontent.com/31863304/130488127-62082160-2073-4a78-b8fe-9f76f37b2519.png)

[Docs link](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size)

**Comment by tonsky** [comment]
So I guess:

EventWindowMaximize
EventWindowMinimize
EventWindowRestore

Is there a separate show/hide on Windows? Is it different from minimize?

**Comment by tonsky** [comment]
Linux: schedule minimize/maximize events after resize
